In [73]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

In [74]:
from sklearn.model_selection import train_test_split

In [75]:
df = pd.read_csv('index.csv')

In [76]:
df.head()

Creditability  Account Balance  Duration of Credit (month)  \
0              1                1                          18   
1              1                1                           9   
2              1                2                          12   
3              1                1                          12   
4              1                1                          12   

   Payment Status of Previous Credit  Purpose  Credit Amount  \
0                                  4        2           1049   
1                                  4        0           2799   
2                                  2        9            841   
3                                  4        0           2122   
4                                  4        0           2171   

   Value Savings/Stocks  Length of current employment  Instalment per cent  \
0                     1                             2                    4   
1                     1                             3                    2   
2                     2                             4                    2   
3                     1                             3                    3   
4                     1                             3                    4   

   Sex & Marital Status  ...  Duration in Current address  \
0                     2  ...                            4   
1                     3  ...                            2   
2                     2  ...                            4   
3                     3  ...                            2   
4                     3  ...                            4   

   Most valuable available asset  Age (years)  Concurrent Credits  \
0                              2           21                   3   
1                              1           36                   3   
2                              1           23                   3   
3                              1           39                   3   
4                              2           38                   1   

   Type of apartment  No of Credits at this Bank  Occupation  \
0                  1                           1           3   
1                  1                           2           3   
2                  1                           1           2   
3                  1                           2           2   
4                  2                           2           2   

   No of dependents  Telephone  Foreign Worker  
0                 1          1               1  
1                 2          1               1  
2                 1          1               1  
3                 2          1               2  
4                 1          1               2  

[5 rows x 21 columns]

In [77]:
df.shape

(1000, 21)

In [78]:
X = df.iloc[:,1:]
y = df.iloc[:, 0]

In [79]:
X.head()

Account Balance  Duration of Credit (month)  \
0                1                          18   
1                1                           9   
2                2                          12   
3                1                          12   
4                1                          12   

   Payment Status of Previous Credit  Purpose  Credit Amount  \
0                                  4        2           1049   
1                                  4        0           2799   
2                                  2        9            841   
3                                  4        0           2122   
4                                  4        0           2171   

   Value Savings/Stocks  Length of current employment  Instalment per cent  \
0                     1                             2                    4   
1                     1                             3                    2   
2                     2                             4                    2   
3                     1                             3                    3   
4                     1                             3                    4   

   Sex & Marital Status  Guarantors  Duration in Current address  \
0                     2           1                            4   
1                     3           1                            2   
2                     2           1                            4   
3                     3           1                            2   
4                     3           1                            4   

   Most valuable available asset  Age (years)  Concurrent Credits  \
0                              2           21                   3   
1                              1           36                   3   
2                              1           23                   3   
3                              1           39                   3   
4                              2           38                   1   

   Type of apartment  No of Credits at this Bank  Occupation  \
0                  1                           1           3   
1                  1                           2           3   
2                  1                           1           2   
3                  1                           2           2   
4                  2                           2           2   

   No of dependents  Telephone  Foreign Worker  
0                 1          1               1  
1                 2          1               1  
2                 1          1               1  
3                 2          1               2  
4                 1          1               2

In [80]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: Creditability, dtype: int64

In [81]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=10)

In [82]:
print(X_train.shape)
print(X_test.shape)

(800, 20)
(200, 20)


In [54]:
rf = RandomForestClassifier()
gb = GradientBoostingClassifier()
svc = SVC()
lr = LogisticRegression()

In [60]:
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
# Evaluate the model
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 29  38]
 [ 14 119]]
              precision    recall  f1-score   support

           0       0.67      0.43      0.53        67
           1       0.76      0.89      0.82       133

    accuracy                           0.74       200
   macro avg       0.72      0.66      0.67       200
weighted avg       0.73      0.74      0.72       200



In [61]:
gb.fit(X_train,y_train)
y_pred = gb.predict(X_test)
accuracy_score(y_test,y_pred)
# Evaluate the model
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 33  34]
 [ 15 118]]
              precision    recall  f1-score   support

           0       0.69      0.49      0.57        67
           1       0.78      0.89      0.83       133

    accuracy                           0.76       200
   macro avg       0.73      0.69      0.70       200
weighted avg       0.75      0.76      0.74       200



In [17]:
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
accuracy_score(y_test,y_pred)

0.665

In [18]:
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
accuracy_score(y_test,y_pred)

c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.715

In [62]:
rf = RandomForestClassifier(max_samples=0.8,random_state=42)
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)
# Evaluate the model
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 30  37]
 [ 15 118]]
              precision    recall  f1-score   support

           0       0.67      0.45      0.54        67
           1       0.76      0.89      0.82       133

    accuracy                           0.74       200
   macro avg       0.71      0.67      0.68       200
weighted avg       0.73      0.74      0.72       200



In [63]:
from sklearn.model_selection import cross_val_score
np.mean(cross_val_score(RandomForestClassifier(max_samples=0.75),X,y,cv=10,scoring='accuracy'))

0.7310000000000001

**GRIDSEARCH**

In [88]:

# Number of trees in random forest
n_estimators = [100, 120]

# Number of features to consider at every split
max_features = [0.8,0.85]

# Maximum number of levels in tree
max_depth = [2,None]

# Number of samples
max_samples = [0.5]

# 108 diff random forest train

In [89]:
param_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
              'max_samples':max_samples
             }

In [90]:
rf = RandomForestClassifier()

In [91]:
from sklearn.model_selection import GridSearchCV

rf_grid = GridSearchCV(estimator = rf, 
                       param_grid = param_grid, 
                       cv = 5, 
                       verbose=2, 
                       n_jobs = -1)

In [92]:
rf_grid.fit(X_train,y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits


exception calling callback for <Future at 0x1ac4c244a88 state=finished raised TerminatedWorkerError>
Traceback (most recent call last):
  File "c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\joblib\externals\loky\_base.py", line 625, in _invoke_callbacks
  File "c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\joblib\parallel.py", line 359, in __call__
    **backend_params
  File "c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\joblib\parallel.py", line 792, in dispatch_next
  File "c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\joblib\parallel.py", line 859, in dispatch_one_batch
    # `TimeoutError` while the callback thread tries to register a result
  File "c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\joblib\parallel.py", line 777, in _dispatch
  File "c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\joblib\_parallel_backends.py", line 531, in apply_async

TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.


In [69]:
rf_grid.best_params_

AttributeError: 'GridSearchCV' object has no attribute 'best_params_'

In [41]:
rf_grid.best_score_

0.78375

In [72]:
rf_grid.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)
# Evaluate the model
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Fitting 5 folds for each of 2 candidates, totalling 10 fits


exception calling callback for <Future at 0x1ac4c1fc988 state=finished raised TerminatedWorkerError>
Traceback (most recent call last):
  File "c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\joblib\externals\loky\_base.py", line 625, in _invoke_callbacks
  File "c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\joblib\parallel.py", line 359, in __call__
    **backend_params
  File "c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\joblib\parallel.py", line 792, in dispatch_next
  File "c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\joblib\parallel.py", line 859, in dispatch_one_batch
    # `TimeoutError` while the callback thread tries to register a result
  File "c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\joblib\parallel.py", line 777, in _dispatch
  File "c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\joblib\_parallel_backends.py", line 531, in apply_async

TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.


In [43]:
rf.feature_importances_

array([0.11430748, 0.10049145, 0.06052218, 0.06197459, 0.13527171,
       0.04289368, 0.053636  , 0.04002006, 0.03624755, 0.01913684,
       0.03934434, 0.04445217, 0.10353784, 0.02551241, 0.0273257 ,
       0.02406663, 0.03343608, 0.01521122, 0.01764757, 0.00496448])