In [15]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

from sklearn.model_selection import train_test_split

df = pd.read_csv('index.csv')

df.head()

df.shape

X = df.iloc[:,1:]
y = df.iloc[:, 0]




X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=10)

print(X_train.shape)
print(X_test.shape)

(800, 20)
(200, 20)


In [54]:
rf = RandomForestClassifier()
gb = GradientBoostingClassifier()
svc = SVC()
lr = LogisticRegression()

In [16]:
print(y_train.shape)
print(y_test.shape)

(800,)
(200,)


In [60]:
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
# Evaluate the model
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 29  38]
 [ 14 119]]
              precision    recall  f1-score   support

           0       0.67      0.43      0.53        67
           1       0.76      0.89      0.82       133

    accuracy                           0.74       200
   macro avg       0.72      0.66      0.67       200
weighted avg       0.73      0.74      0.72       200



In [61]:
gb.fit(X_train,y_train)
y_pred = gb.predict(X_test)
accuracy_score(y_test,y_pred)
# Evaluate the model
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 33  34]
 [ 15 118]]
              precision    recall  f1-score   support

           0       0.69      0.49      0.57        67
           1       0.78      0.89      0.83       133

    accuracy                           0.76       200
   macro avg       0.73      0.69      0.70       200
weighted avg       0.75      0.76      0.74       200



In [17]:
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
accuracy_score(y_test,y_pred)

0.665

In [18]:
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
accuracy_score(y_test,y_pred)

c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.715

In [62]:
rf = RandomForestClassifier(max_samples=0.8,random_state=42)
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)
# Evaluate the model
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 30  37]
 [ 15 118]]
              precision    recall  f1-score   support

           0       0.67      0.45      0.54        67
           1       0.76      0.89      0.82       133

    accuracy                           0.74       200
   macro avg       0.71      0.67      0.68       200
weighted avg       0.73      0.74      0.72       200



In [63]:
from sklearn.model_selection import cross_val_score
np.mean(cross_val_score(RandomForestClassifier(max_samples=0.75),X,y,cv=10,scoring='accuracy'))

0.7310000000000001

**GRIDSEARCH**

In [11]:

# Number of trees in random forest
n_estimators = [100, 120]

# Number of features to consider at every split
max_features = [0.8,0.85]

# Maximum number of levels in tree
max_depth = [2,None]

# Number of samples
max_samples = [0.5]

# 108 diff random forest train

param_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
              'max_samples':max_samples
             }

rf_grid_rf = RandomForestClassifier()

from sklearn.model_selection import GridSearchCV

rf_grid = GridSearchCV(estimator = rf_grid_rf, 
                       param_grid = param_grid, 
                       cv = 5, 
                       verbose=2, 
                       n_jobs = -1)

rf_grid.fit(X_train,y_train)

In [69]:
rf_grid.best_params_

AttributeError: 'GridSearchCV' object has no attribute 'best_params_'

In [41]:
rf_grid.best_score_

0.78375

In [72]:
rf_grid.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)
# Evaluate the model
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

rf.feature_importances_

Fitting 5 folds for each of 2 candidates, totalling 10 fits


exception calling callback for <Future at 0x1ac4c1fc988 state=finished raised TerminatedWorkerError>
Traceback (most recent call last):
  File "c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\joblib\externals\loky\_base.py", line 625, in _invoke_callbacks
  File "c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\joblib\parallel.py", line 359, in __call__
    **backend_params
  File "c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\joblib\parallel.py", line 792, in dispatch_next
  File "c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\joblib\parallel.py", line 859, in dispatch_one_batch
    # `TimeoutError` while the callback thread tries to register a result
  File "c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\joblib\parallel.py", line 777, in _dispatch
  File "c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\joblib\_parallel_backends.py", line 531, in apply_async

TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.
